#!/usr/bin/env lua

-- Add the sketchybar module to the package cpath (the module could be
-- installed into the default search path then this would not be needed)
local home = os.getenv("HOME")
if home then
	package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"
end

-- Require the sketchybar module
sbar = require("sketchybar")

require("init")
sbar.hotload(true)
